// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriBreak.Persistence;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NutriBreak.Migrations
{
    [DbContext(typeof(NutriBreakDbContext))]
    [Migration("20251123170645_DecimalIdsInitial")]
    partial class DecimalIdsInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriBreak.Domain.BreakRecord", b =>
                {
                    b.Property<decimal>("Id")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("ScreenTimeMinutes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<decimal>("UserId")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BreakRecords");
                });

            modelBuilder.Entity("NutriBreak.Domain.Meal", b =>
                {
                    b.Property<decimal>("Id")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Calories")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<decimal>("UserId")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("NutriBreak.Domain.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutriBreak.Domain.BreakRecord", b =>
                {
                    b.HasOne("NutriBreak.Domain.User", "User")
                        .WithMany("Breaks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriBreak.Domain.Meal", b =>
                {
                    b.HasOne("NutriBreak.Domain.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriBreak.Domain.User", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
